rm=(list=ls())
a = read.csv("bpcoll_current.csv",stringsAsFactors=FALSE)
bpcoll = data.frame(bptime=strptime(a$timestamp,'%Y-%m-%d %H:%M'),sbp=a$sbp,dbp=a$dbp)
png(filename="bpcoll_current.png",width=640,height=480)
plot(sbp~bptime,data=bpcoll,ylim=c(50,200),type="o",ylab="",xlab="",col="blue",lwd=3)
lines(dbp~bptime,data=bpcoll,col="blue",lwd=3,type="o")
abline(h=c(seq(50,200,10)))
abline(h=c(seq(50,200,50)),lwd=3)
abline(h=c(90,140),lwd=2,col="red")
title(main="Systolic and Diastolic Blood Pressure")
dev.off()
